// examples/ssr-vite-qwik/src/store.ts
import {
  createContextId,
  useContext
} from '@builder.io/qwik'
import { type State, connectState } from 'class-state'

export const PROVIDE_STORE_KEY = createContextId<State>(
  'class-state'
)

export function useState (): State {
  return useContext(PROVIDE_STORE_KEY)
}

export class Count {
  public static use (state: State = useState()) {
    return connectState(state)(this, 'count')
  }

  public value: number = 0
  public now: string = ''
  public $inc () {
    this.value++
  }

  public $dec () {
    this.value--
  }

  public $updateTime () {
    this.now = new Date().toISOString()
  }
}

// examples/ssr-react/src/store.ts
import { createContext, useContext, useSyncExternalStore } from 'react'

import { type State, connectState } from 'class-state'

// 创建状态的上下文
export const StateContext = createContext<State>({
  value: {}
})

// 获取状态
export function useState (): State {
  return useContext(StateContext)
}

// 定义类
export class Count {
  // 定义使用方法
  public static use (state: State = useState()) {
    const count = connectState(state)(this, 'count')
    return useSyncExternalStore(count.$.subscribe, count.$.get, count.$.get)
  }

  // 定义值
  public value: number = 0
  // 值加加
  public $inc () {
    this.value++
  }

  // 值减减
  public $dec () {
    this.value--
  }
}
