// examples/ssr-vite-qwik/src/child.tsx
import { component$ } from '@builder.io/qwik'
import { useState, Count } from './store'

export const Child = component$(() => {
  const state = useState()
  return (
        <div>
            <button onClick$={() => {
              Count.use(state).$inc()
            }}>+</button>
            <button onClick$={() => {
              Count.use(state).$dec()
            }}>-</button>
        </div>
  )
})

// examples/ssr-vite-react/src/child.tsx
import { Count } from './store'

export const Child = () => {
  const count = Count.use()
  return (
          <div>
              <button onClick={() => {
                count.$inc()
              }}>+</button>
              <button onClick={() => {
                count.$dec()
              }}>-</button>
          </div>
  )
}
