// examples/ssr-qwik/src/app.tsx
import { createState } from 'class-state'
import {
  component$,
  useStore,
  useVisibleTask$,
  useContextProvider,
  useTask$
} from '@builder.io/qwik'
import { Count, PROVIDE_STORE_KEY } from './store'
import { Child } from './child'

const App = component$(() => {
  const state = createState(useStore({ value: {} }))

  useContextProvider(PROVIDE_STORE_KEY, state)

  // 客户端需要激活状态
  useVisibleTask$(async () => {
    createState(state)
  })

  const count = Count.use()

  // 模拟服务端请求
  useTask$(async () => {
    await new Promise<void>((resolve) => {
      setTimeout(() => {
        Count.use(state).$setTime()
        resolve()
      }, 200)
    })
  })

  // 客户端继续更新状态
  useVisibleTask$((taskContext) => {
    const timer = setInterval(Count.use(state).$setTime, 1000)

    taskContext.cleanup(() => {
      clearInterval(timer)
    })
  })

  return (
    <>
      <head>
        <title>{count.serverTime}</title>
      </head>
      <body>
        <div class="app">
          <p>Current Time: {count.serverTime}</p>
          <Child />
          <p>Click Count: {count.value}</p>
        </div>
      </body>
    </>
  )
})

export const AppNode = <App />

// examples/ssr-vite-vue3/src/app.vue
<template>
    <div class="app">
        <p>Current Time: {{ count.serverTime }}</p>
        <Child />
        <p>Click Count: {{ count.value }}</p>
    </div>
</template>
<script setup lang="ts">
import { onServerPrefetch, onMounted, onBeforeUnmount } from 'vue';
import { Count } from './store'
import Child from './child.vue';

const count = Count.use()

// 模拟服务端请求调用
onServerPrefetch(() => {
    return new Promise<void>((resolve) => {
        setTimeout(() => {
            count.$setTime()
            resolve()
        }, 200)
    })
})

// 客户端接管服务端状态后，继续更新状态
onMounted(() => {
    const timer = setInterval(count.$setTime, 1000)
    onBeforeUnmount(() => {
        // 组件销毁时，清理定时器
        clearInterval(timer)
    })
})
</script>
