// examples/ssr-vite-react/src/child.tsx
import { Count } from './store'

export const Child = () => {
  const count = Count.use()
  return (
          <div>
              <button onClick={() => {
                count.$inc()
              }}>+</button>
              <button onClick={() => {
                count.$dec()
              }}>-</button>
          </div>
  )
}

// examples/ssr-vue2/src/child.vue
<template>
    <div>
        <button class="btn" @click="count.$inc()">+</button>
        <button class="btn" @click="count.$dec()">-</button>
    </div>
</template>
<script lang="ts" setup>
import { Count } from './store';

const count = Count.use()

</script>
<style scoped>
.btn {
    padding: 5px 10px;
    margin: 0 5px;
    cursor: pointer;
}
</style>
